// Maintained by Trust & Safety. Matching is case-insensitive and tolerant of
// spacing and punctuation between letters ("w h a t s a p p", "t.e.l.e.g.r.a.m").
export const BLOCKED_TERMS: string[] = [
  'whatsapp',
  'telegram',
  'wechat',
  'signal me',
  'dm me',
  'text me',
  'call me',
  'email me',
  'contact me',
  'message me',
  'inbox me',
  'reach me at',
  'my number',
  'phone number',
  'cash app',
  'cashapp',
  'venmo',
  'zelle',
  'paypal me',
  'western union',
  'moneygram',
  'wire transfer',
  'bank transfer',
  'gift card',
  'itunes card',
  'bitcoin',
  'btc',
  'ethereum',
  'crypto',
  'usdt',
  'binance',
  'coinbase',
  'investment opportunity',
  'double your money',
  'make money fast',
  'work from home',
  'earn cash',
  'free money',
  'free gift',
  'free iphone',
  'giveaway',
  'click here',
  'click the link',
  'visit my',
  'check my profile',
  'follow me',
  'subscribe',
  'promo code',
  'discount code',
  'coupon code',
  'referral code',
  'use my code',
  'cheaper at',
  'buy direct',
  'buy directly',
  'off platform',
  'outside bazario',
  'better price at',
  'dropship',
  'wholesale price',
  'bit.ly',
  'tinyurl',
  'goo.gl',
  't.me',
  'wa.me',
  'http',
  'https',
  'www',
  'dot com',
  'onlyfans',
  'casino',
  'betting',
  'lottery',
  'loan offer',
  'payday loan',
  'viagra',
  'cialis',
  'weight loss pills',
  'diet pills',
  'replica',
  'counterfeit',
  'knockoff',
  'fake',
  'scam',
  'scammer',
  'fraud',
  'stolen',
  'hack',
  'hacked',
  'cracked',
  'pirated',
  'torrent',
  'crap',
  'damn',
  'idiot',
  'stupid',
  'moron',
  'dumb',
  'loser',
  'garbage seller',
  'rip off',
  'ripoff',
  'sucks',
  'shut up',
  'hate this seller',
];
